const test=require('node:test'),assert=require('node:assert/strict');
const {service}=require('../cloudfunctions/treehole/service');const {memoryRepo}=require('./memory-repo.cjs');
function setup(){const repo=memoryRepo();const handle=service(repo);return {repo,handle,publish:()=>handle({action:'publish',operationId:'publish1',id:'note1',body:'hello',sig:''},'owner')};}
test('server trusts caller context, not client owner field',async()=>{const {handle,publish}=setup();await publish();await assert.rejects(handle({action:'withdraw',id:'note1',operationId:'withdraw1',owner:'owner'},'attacker'),/FORBIDDEN/);await assert.rejects(handle({action:'hello'},''),/AUTH_REQUIRED/);});
test('concurrent replies and reactions survive and deduplicate',async()=>{const {handle,publish}=setup();await publish();await Promise.all(Array.from({length:8},(_,i)=>handle({action:'reply',id:'note1',operationId:'reply'+i,body:'reply '+i},'visitor'+i)));await Promise.all(Array.from({length:8},(_,i)=>handle({action:'light',id:'note1',operationId:'light'+i},'visitor'+i)));await handle({action:'light',id:'note1',operationId:'light-new'},'visitor1');const {notes}=await handle({action:'list'},'owner');assert.equal(notes[0].replies.length,8);assert.equal(notes[0].lights,8);assert.equal(notes[0].owner,undefined);});
test('retry is idempotent and does not expose withdrawn content',async()=>{const {handle,publish,repo}=setup();await publish();await publish();await handle({action:'reply',id:'note1',operationId:'r1',body:'private reply'},'visitor');await handle({action:'withdraw',id:'note1',operationId:'w1'},'owner');const retry=await publish();assert.equal(retry.note.status,'withdrawn');assert.equal(retry.note.bodyCn,'');assert.equal(retry.note.replies.length,0);assert.equal(JSON.stringify(repo.snapshot()).includes('private reply'),false);await assert.rejects(handle({action:'reply',id:'note1',operationId:'r2',body:'late'},'visitor'),/WITHDRAWN/);});
test('reports are stored with a traceable receipt',async()=>{const {handle,publish,repo}=setup();await publish();const result=await handle({action:'report',id:'note1',operationId:'report1'},'visitor');const report=await repo.get(null,'rc_reports',result.reportId);assert.equal(report.noteId,'note1');assert.equal(report.status,'pending');});
test('input length and rate limit are enforced on server',async()=>{const {handle,publish}=setup();await assert.rejects(handle({action:'publish',id:'long',operationId:'long',body:'x'.repeat(141)},'owner'),/INVALID_INPUT/);await publish();for(let i=0;i<19;i++)await handle({action:'light',id:'note1',operationId:'op'+i},'owner');await assert.rejects(handle({action:'light',id:'note1',operationId:'over'},'owner'),/RATE_LIMIT/);});
test('known withdrawn notes are returned beyond the feed window',async()=>{const {handle,repo,publish}=setup();await publish();await handle({action:'withdraw',id:'note1',operationId:'w'},'owner');for(let i=0;i<90;i++)await repo.set(null,'rc_notes','other'+i,{id:'other'+i,status:'published',updatedAt:Date.now()+i,owner:'other',replies:[]});const result=await handle({action:'list',known:['note1']},'visitor');assert.equal(result.notes.find(n=>n.id==='note1').status,'withdrawn');});
