<script setup lang="ts">
import {ref,watch} from 'vue';import {rc} from './legacy';import type {SiteContent} from './content';
const props=defineProps<{request:<T>(body:unknown)=>Promise<T>}>();
const content=ref<SiteContent>({revision:0,items:{},chapters:{}}),group=ref('items'),id=ref('milk'),draft=ref<Record<string,string>>({}),message=ref(''),busy=ref(false);
function select(){const source=group.value==='items'?content.value.items[id.value]||rc.bar.menu.find(d=>d.id===id.value):content.value.chapters[id.value];draft.value={};for(const k of group.value==='items'?['cn','jp','desc','descJp','line','lineJp']:['cn','jp'])draft.value[k]=(source as Record<string,string>|undefined)?.[k]||'';}
watch(id,select);watch(group,()=>{id.value=group.value==='items'?'milk':'1';select();});select();
async function load(){try{content.value=await props.request<SiteContent>({action:'content:get'});select();message.value='已载入当前内容。 / 読み込みました。';}catch{message.value='读取失败。 / 読み込みに失敗しました。';}}
async function save(){if(busy.value)return;busy.value=true;try{content.value=await props.request<SiteContent>({action:'content:save',revision:content.value.revision,group:group.value,id:id.value,value:draft.value});message.value='已发布。新打开的页面会读取这份内容。 / 公開しました。';}catch{message.value='发布失败，可能已被其他管理员修改。请重新载入后再编辑。 / 公開できませんでした。';}finally{busy.value=false;}}
</script>
<template><section><h2>店主管理 · 内容编辑 / コンテンツ</h2><button @click="load">载入当前内容 / 読み込む</button><label>编辑类型 / 種類<select v-model="group"><option value="items">菜品与酒保台词 / メニュー</option><option value="chapters">章节附记 / 章の追記</option></select></label><label>选择内容 / 選択<select v-model="id"><template v-if="group==='items'"><option v-for="d in rc.bar.menu" :key="d.id" :value="d.id">{{d.cn}}</option></template><template v-else><option v-for="n in 5" :key="n" :value="String(n)">第 {{n}} 章</option></template></select></label><label v-for="field in Object.keys(draft)" :key="field">{{({cn:group==='items'?'中文名称':'中文附记',jp:group==='items'?'日本語名':'日本語の追記',desc:'中文介绍',descJp:'日本語の説明',line:'中文酒保台词',lineJp:'日本語のセリフ'} as Record<string,string>)[field]}}<textarea v-model="draft[field]" maxlength="1000" rows="3"></textarea></label><button :disabled="busy" @click="save">发布这项修改 / 公開</button><p role="status">{{message}}</p></section></template>
<style scoped>select,textarea{display:block;box-sizing:border-box;width:100%;margin-top:8px;padding:10px;background:#12160e;color:#e3d8b9;border:1px solid #5a6145;font:inherit}textarea{resize:vertical}</style>
